services:
  - type: web
    name: ecofy-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node app.js
    plan: free
    autoDeploy: true
    envVars:
      - key: MONGO_URI
      - key: PORT
        value: 8082
      - key: NODE_ENV
        value: production
